language: node_js
node_js:
  - '8'
install:
  - yarn install
script:
  - yarn run lint
  - yarn run coverage
after_script:
  - cat coverage/lcov.info | node_modules/.bin/coveralls
notifications:
  email:
    on_success: change
    on_failure: always
